# Limpeza de Dados (data-cleaning)

In [58]:
import pandas as pd
df = pd.read_csv("british_library.csv")
df

,Identifier,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL,Shelfmarks
0,206,NaN,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12641.b.30.
1,216,NaN,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.
2,218,NaN,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12625.dd.1.
3,472,NaN,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10369.bbb.15.
4,480,"A new edition, revised, etc.",London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9007.d.28.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8282,4158088,NaN,London,1838,NaN,"The Parochial History of Cornwall, founded on,...","GIDDY, afterwards GILBERT, Davies.","BOASE, Henry Samuel.|HALS, William.|LYSONS, Da...",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...
8283,4158128,NaN,Derby,"1831, 32",M. Mozley & Son,The History and Gazetteer of the County of Der...,"GLOVER, Stephen - of Derby","NOBLE, Thomas.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...
8284,4159563,NaN,London,[1806]-22,T. Cadell and W. Davies,Magna Britannia; being a concise topographical...,"LYSONS, Daniel - M.A., F.R.S., and LYSONS (Sam...","GREGSON, Matthew.|LYSONS, Samuel - F.R.S",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 19...
8285,4159587,NaN,Newcastle upon Tyne,1834,Mackenzie & Dent,"An historical, topographical and descriptive v...","Mackenzie, E. (Eneas)","ROSS, M. - of Durham",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...
8286,4160339,NaN,London,1834-43,NaN,Collectanea Topographica et Genealogica. [Firs...,NaN,"BANDINEL, Bulkeley.|Nichols, John Gough",NaN,NaN,NaN,NaN,continuing,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 79...

In [59]:
df.info()
# Mostra muitas colunas com dados nulos que de nada servem

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8287 entries, 0 to 8286
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Identifier              8287 non-null   int64
 1   Edition Statement       773 non-null    object
 2   Place of Publication    8287 non-null   object
 3   Date of Publication     8106 non-null   object
 4   Publisher               4092 non-null   object
 5   Title                   8287 non-null   object
 6   Author                  6509 non-null   object
 7   Contributors            8287 non-null   object
 8   Corporate Author        0 non-null      float64
 9   Corporate Contributors  0 non-null      float64
 10  Former owner            1 non-null      object
 11  Engraver                0 non-null      float64
 12  Issuance type           8287 non-null   object
 13  Flickr URL              8287 non-null   object
 14  Shelfmarks              8287 non-null   object
dtypes: float64(3), int64(1), object(11)
memory usage: 971.3+ KB

In [60]:
# Então vamos apagar essas colunas.
df.drop(
    columns=[
        'Edition Statement', 
        'Corporate Author', 
        'Corporate Contributors', 
        'Former owner', 
        'Engraver'])

,Identifier,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Issuance type,Flickr URL,Shelfmarks
0,206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12641.b.30.
1,216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.
2,218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12625.dd.1.
3,472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10369.bbb.15.
4,480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9007.d.28.
...,...,...,...,...,...,...,...,...,...,...
8282,4158088,London,1838,NaN,"The Parochial History of Cornwall, founded on,...","GIDDY, afterwards GILBERT, Davies.","BOASE, Henry Samuel.|HALS, William.|LYSONS, Da...",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...
8283,4158128,Derby,"1831, 32",M. Mozley & Son,The History and Gazetteer of the County of Der...,"GLOVER, Stephen - of Derby","NOBLE, Thomas.",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...
8284,4159563,London,[1806]-22,T. Cadell and W. Davies,Magna Britannia; being a concise topographical...,"LYSONS, Daniel - M.A., F.R.S., and LYSONS (Sam...","GREGSON, Matthew.|LYSONS, Samuel - F.R.S",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 19...
8285,4159587,Newcastle upon Tyne,1834,Mackenzie & Dent,"An historical, topographical and descriptive v...","Mackenzie, E. (Eneas)","ROSS, M. - of Durham",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...
8286,4160339,London,1834-43,NaN,Collectanea Topographica et Genealogica. [Firs...,NaN,"BANDINEL, Bulkeley.|Nichols, John Gough",continuing,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 79...

In [61]:
# Se observarmos as colunas ainda existem.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8287 entries, 0 to 8286
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Identifier              8287 non-null   int64
 1   Edition Statement       773 non-null    object
 2   Place of Publication    8287 non-null   object
 3   Date of Publication     8106 non-null   object
 4   Publisher               4092 non-null   object
 5   Title                   8287 non-null   object
 6   Author                  6509 non-null   object
 7   Contributors            8287 non-null   object
 8   Corporate Author        0 non-null      float64
 9   Corporate Contributors  0 non-null      float64
 10  Former owner            1 non-null      object
 11  Engraver                0 non-null      float64
 12  Issuance type           8287 non-null   object
 13  Flickr URL              8287 non-null   object
 14  Shelfmarks              8287 non-null   object
dtypes: float64(3), int64(1), object(11)
memory usage: 971.3+ KB

In [49]:
# Para deletar realmente as colunas temos de usar inplace()
df.drop(
    columns=[
        'Edition Statement', 
        'Corporate Author', 
        'Corporate Contributors', 
        'Former owner', 
        'Engraver'], inplace=True)

In [62]:
# Ao usar inplace percebemos que as colunas realmente desapareceram.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8287 entries, 0 to 8286
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Identifier              8287 non-null   int64
 1   Edition Statement       773 non-null    object
 2   Place of Publication    8287 non-null   object
 3   Date of Publication     8106 non-null   object
 4   Publisher               4092 non-null   object
 5   Title                   8287 non-null   object
 6   Author                  6509 non-null   object
 7   Contributors            8287 non-null   object
 8   Corporate Author        0 non-null      float64
 9   Corporate Contributors  0 non-null      float64
 10  Former owner            1 non-null      object
 11  Engraver                0 non-null      float64
 12  Issuance type           8287 non-null   object
 13  Flickr URL              8287 non-null   object
 14  Shelfmarks              8287 non-null   object
dtypes: float64(3), int64(1), object(11)
memory usage: 971.3+ KB

In [63]:
df.head()

,Identifier,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL,Shelfmarks
0,206,NaN,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12641.b.30.
1,216,NaN,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.
2,218,NaN,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12625.dd.1.
3,472,NaN,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10369.bbb.15.
4,480,"A new edition, revised, etc.",London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9007.d.28.

**OBS.: Agora já com as colunas nulas eliminadas temos algumas sobre dados que são ou não realmente úteis: URL, Data de publicação em formatos diferentes, Número de Identificação...**

In [64]:
# O Identifier, ou seja, número de identificação pode ser muito importante na minha análise.
# Ao analisar vemos que realmente a coluna tem valores únicos.
df['Identifier'].is_unique

True

In [22]:
df.tail()

,Identifier,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Issuance type,Flickr URL,Shelfmarks
8282,4158088,London,1838,NaN,"The Parochial History of Cornwall, founded on,...","GIDDY, afterwards GILBERT, Davies.","BOASE, Henry Samuel.|HALS, William.|LYSONS, Da...",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...
8283,4158128,Derby,"1831, 32",M. Mozley & Son,The History and Gazetteer of the County of Der...,"GLOVER, Stephen - of Derby","NOBLE, Thomas.",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...
8284,4159563,London,[1806]-22,T. Cadell and W. Davies,Magna Britannia; being a concise topographical...,"LYSONS, Daniel - M.A., F.R.S., and LYSONS (Sam...","GREGSON, Matthew.|LYSONS, Samuel - F.R.S",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 19...
8285,4159587,Newcastle upon Tyne,1834,Mackenzie & Dent,"An historical, topographical and descriptive v...","Mackenzie, E. (Eneas)","ROSS, M. - of Durham",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...
8286,4160339,London,1834-43,NaN,Collectanea Topographica et Genealogica. [Firs...,NaN,"BANDINEL, Bulkeley.|Nichols, John Gough",continuing,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 79...

In [65]:
df.value_counts('Issuance type')

Issuance type
monographic    8268
continuing       19
Name: count, dtype: int64

In [66]:
df[df['Issuance type'] == 'continuing']

,Identifier,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL,Shelfmarks
1420,637013,[Another edition.],London,[1846],"Fisher, Son & Co.",[The Great Civil War of Charles I. and the Par...,"CATTERMOLE, Richard.","Cattermole, George",NaN,NaN,NaN,NaN,continuing,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 789.d.19.
2148,946856,NaN,Richmond,1866,Gary & Clemmitr,The City of Richmond Business Directory and Ci...,NaN,"MILLS, S. Dow - and STARKE (Horace W.)|STARKE,...",NaN,NaN,NaN,NaN,continuing,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS P.P.2534.p.|British Libr...
2454,1169627,NaN,Windsor,1819,Knight & Son,Poetry of the College Magazine. [The editors p...,NaN,"B., W.|BLUNT, Walter.",NaN,NaN,NaN,NaN,continuing,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS P.P.6127.|British Librar...
4158,2048675,NaN,Harrison & Co,"1781, 82",London,"The lady's poetical magazine, or Beauties of B...",NaN,"HEATH, James - A.R.A|Stothard, Thomas",NaN,NaN,NaN,NaN,continuing,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS P.P.5126.|British Librar...
5784,2824693,NaN,Augsburg,1829,NaN,Auszüge aus den eingesendeten Beiträgen zu B...,NaN,"RAISER, Johann Nepomuk von.",NaN,NaN,NaN,NaN,continuing,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10250.f.7.
5785,2825196,NaN,Belfast,"1853, [1853-55]",NaN,The Annals of Ulster. Translated from the text...,NaN,"O'CONOR, Charles - D.D",NaN,NaN,NaN,NaN,continuing,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS P.P.1925.g.(2.)|British ...
5786,2827691,NaN,Breslau,1805-07,NaN,Topographische Chronik von Breslau [by C. A. M...,NaN,"MENZEL, Carl Adolf.",NaN,NaN,NaN,NaN,continuing,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10261.f.8.
5787,2830716,NaN,Чернівцї,1897,NaN,Буковинська Русь. Культурно-історичний образок...,NaN,"SMAL'-STOTS'KY, Stefan.",NaN,NaN,NaN,NaN,continuing,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 010290.eee.73.
5788,2831037,NaN,Dordrecht,1858,NaN,Dordrecht. Door ... G. D. J. Schotel. no. 1,NaN,"SCHOTEL, Gilles Denijs Jacob.",NaN,NaN,NaN,NaN,continuing,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10271.e.13.
5789,2839670,NaN,London,"[1860, etc.]",NaN,Beeton's Christmas Annual. Edited by the publi...,NaN,"BEETON, Samuel Orchart.",NaN,NaN,NaN,NaN,continuing,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS P.P.6704.|British Librar...
5790,2839703,NaN,London,1876,NaN,"The Bentley Ballards, etc: Bentley's Miscellan...",NaN,"SHEEHAN, John.",NaN,NaN,NaN,NaN,continuing,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 11646.g.34.
5791,2841017,NaN,London,1853-55,NaN,The Cheshire and Lancashire Historical Collect...,NaN,"BARLOW, Thomas Worthington.",NaN,NaN,NaN,NaN,continuing,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10352.h.20.
5792,2855619,NaN,London,"1795, 96",NaN,The Tribune. ... Consisting chiefly of the pol...,NaN,"RAMSEY, William - Shorthand Writer|THELWALL, J...",NaN,NaN,NaN,NaN,continuing,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12270.pp.6.
5794,2856780,NaN,London,1886,NaN,"Worthy Workers. A monthly magazine for all, et...",NaN,"Sutton, Sarah.",NaN,NaN,NaN,NaN,continuing,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 012272.ee.12.(5.)
5795,2861949,NaN,Great Yarmouth,1887,NaN,Norwich Mercury. Yarmouth Notes. First(-fourth...,NaN,"PALMER, Frederick Danby.",NaN,NaN,NaN,NaN,continuing,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 010358.e.28.
5796,2868249,NaN,Rouen,1887,NaN,"L'Année Rouennaise. Rouen en 1886, (Émile De...",NaN,"DESHAYS, Émile.",NaN,NaN,NaN,NaN,continuing,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10171.i.5.
5797,2868655,NaN,Scarborough,1824,NaN,"Scarborough Repository, and Mirror of the Seas...",NaN,"COLE, John - of Scarborough",NaN,NaN,NaN,NaN,continuing,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 796.f.27.
5798,2869620,NaN,Stokesley,1823,NaN,The Missionary; or Stokesley and Cleveland Ill...,NaN,"MEASE, Thomas.",NaN,NaN,NaN,NaN,continuing,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10347.f.32.(3.)
8286,4160339,NaN,London,1834-43,NaN,Collectanea Topographica et Genealogica. [Firs...,NaN,"BANDINEL, Bulkeley.|Nichols, John Gough",NaN,NaN,NaN,NaN,continuing,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 79...

In [67]:
df['Shelfmarks'].is_unique

True

**Shelfmarks também é campo único e sua única utilidade poderá ser o uso como INDEX. Mas para isso temos um melhor identificador único, que é o identifier visto acima. Logo, podemos deletar essa coluna.?**

In [68]:
df.drop(
    columns=[
        'Shelfmarks', 
        ], inplace=True)

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8287 entries, 0 to 8286
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Identifier              8287 non-null   int64
 1   Edition Statement       773 non-null    object
 2   Place of Publication    8287 non-null   object
 3   Date of Publication     8106 non-null   object
 4   Publisher               4092 non-null   object
 5   Title                   8287 non-null   object
 6   Author                  6509 non-null   object
 7   Contributors            8287 non-null   object
 8   Corporate Author        0 non-null      float64
 9   Corporate Contributors  0 non-null      float64
 10  Former owner            1 non-null      object
 11  Engraver                0 non-null      float64
 12  Issuance type           8287 non-null   object
 13  Flickr URL              8287 non-null   object
dtypes: float64(3), int64(1), object(10)
memory usage: 906.5+ KB

In [70]:
# Como foi decidido acima vamos deixar a coluna Identifier como índice
df.set_index('Identifier', inplace=True)

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8287 entries, 206 to 4160339
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Edition Statement       773 non-null    object
 1   Place of Publication    8287 non-null   object
 2   Date of Publication     8106 non-null   object
 3   Publisher               4092 non-null   object
 4   Title                   8287 non-null   object
 5   Author                  6509 non-null   object
 6   Contributors            8287 non-null   object
 7   Corporate Author        0 non-null      float64
 8   Corporate Contributors  0 non-null      float64
 9   Former owner            1 non-null      object
 10  Engraver                0 non-null      float64
 11  Issuance type           8287 non-null   object
 12  Flickr URL              8287 non-null   object
dtypes: float64(3), object(10)
memory usage: 906.4+ KB

In [72]:
df

,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL
Identifier,,,,,,,,,,,,,
206,NaN,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...
216,NaN,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...
218,NaN,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...
472,NaN,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...
480,"A new edition, revised, etc.",London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4158088,NaN,London,1838,NaN,"The Parochial History of Cornwall, founded on,...","GIDDY, afterwards GILBERT, Davies.","BOASE, Henry Samuel.|HALS, William.|LYSONS, Da...",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...
4158128,NaN,Derby,"1831, 32",M. Mozley & Son,The History and Gazetteer of the County of Der...,"GLOVER, Stephen - of Derby","NOBLE, Thomas.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...
4159563,NaN,London,[1806]-22,T. Cadell and W. Davies,Magna Britannia; being a concise topographical...,"LYSONS, Daniel - M.A., F.R.S., and LYSONS (Sam...","GREGSON, Matthew.|LYSONS, Samuel - F.R.S",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...
4159587,NaN,Newcastle upon Tyne,1834,Mackenzie & Dent,"An historical, topographical and descriptive v...","Mackenzie, E. (Eneas)","ROSS, M. - of Durham",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...
4160339,NaN,London,1834-43,NaN,Collectanea Topographica et Genealogica. [Firs...,NaN,"BANDINEL, Bulkeley.|Nichols, John Gough",NaN,NaN,NaN,NaN,continuing,http://www.flickr.com/photos/britishlibrary/ta...

In [73]:
df[:100]

,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL
Identifier,,,,,,,,,,,,,
206,NaN,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...
216,NaN,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...
218,NaN,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...
472,NaN,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...
480,"A new edition, revised, etc.",London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
36521,[Another edition.] With memoir and critical di...,Edinburgh,1857,James Nichol,[The Poetical Works of Mark Akenside ... With ...,"Akenside, Mark","Gilfillan, George",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...
36531,NaN,Napoli,1821,NaN,[Hymn to the Naiads.] Alle Najadi. Inno alla G...,"AKENSIDE, Mark.","MATHIAS, Thomas James.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...
36721,NaN,London,1897,Bliss & Sands,Triscombe Stone: a romance of the Quantock Hil...,"AKERMAN, Portland Board - and HURST (Norman)","HURST, Norman.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...
38673,NaN,Ἐν Κερκυρᾳ,1891,NaN,Κερκυραϊκα ἀπομνημονευματα. [Edited by I. De...,"ALBANAS, Phriderikos.","DELOTES, I.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...
38986,NaN,London,1827,William Marsh,Scenes and Occurrences in Albany and Cafferlan...,NaN,"PHILLIPS, T. - Rev., Baptist Missionary",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...